/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Universal-Document-Parser.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Universal Document Parser
 #	author : miyako
 #	2026/03/30
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Universal-Document-Parser.h"

#pragma mark -

chunker::ChunkerPtr gchunker;
int32_t gpadtoken_id;

static void OnStartup() {
    FPDF_InitLibrary();
}

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
            case kInitPlugin :
            case kServerInitPlugin :
                OnStartup();
                break;
             
            case kDeinitPlugin :
            case kServerDeinitPlugin :
                OnExit();
                break;
                
			// --- Universal Document Parser
            
			case 1 :
				Extract(params);
				break;
            case 2 :
                Extract_SET_OPTION(params);
                break;
        }

	}
	catch(...)
	{

	}
}

#pragma mark 4D.File

static bool _object_to_path(PA_ObjectRef f, std::string& path, int type) {
 
    if(f != NULL) {
        C_TEXT pp;
        pp.setUTF8String((const uint8_t *)"platformPath", 12);
        PA_Unistring PLATFORMPATH = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());//PA_DisposeUnistring
        PA_VariableKind vk = PA_GetObjectPropertyType(f, &PLATFORMPATH);
        if(vk == eVK_Unistring) {
            PA_Variable p = PA_GetObjectProperty(f, &PLATFORMPATH);//PA_ClearVariable
            PA_Variable cbparams[2];
            cbparams[0] = PA_CreateVariable(eVK_Unistring);//PA_DisposeUnistring
            cbparams[1] = PA_CreateVariable(eVK_Longint);//PA_DisposeUnistring
            PA_Unistring platformPath = PA_GetStringVariable(p);
            PA_SetStringVariable(&cbparams[0], &platformPath);
            PA_SetLongintVariable(&cbparams[1], 1/*fk platform path*/);
            PA_Variable folder = PA_ExecuteCommandByID(type, cbparams, 2);
            PA_ClearVariable(&cbparams[0]);
            PA_ClearVariable(&cbparams[1]);
            PA_ClearVariable(&p);
            
#if VERSIONMAC
            pp.setUTF8String((const uint8_t *)"path", 4);
            PA_Unistring PATH = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());//PA_DisposeUnistring
            PA_Variable _p = PA_GetObjectProperty(PA_GetObjectVariable(folder), &PATH);//PA_ClearVariable
            platformPath = PA_GetStringVariable(_p);
            PA_DisposeUnistring(&PATH);
            PA_ClearVariable(&_p);
#endif
            C_TEXT t;
            t.setUTF16String(&platformPath);
            CUTF8String u8;
            t.copyUTF8String(&u8);
            path = std::string((const char *)u8.c_str(), u8.size());
        }
        PA_DisposeUnistring(&PLATFORMPATH);
        return (vk == eVK_Unistring);
    }
    
    return false;
}

static bool file_object_to_data(PA_ObjectRef f, std::vector<uint8_t>& data) {
    
    if(f != NULL) {
        
        const int cmd_4D = 1709;
        PA_Variable prm_4D[1];
        PA_Variable _4D = PA_ExecuteCommandByID(cmd_4D, prm_4D, 0);
        
        const int cmd_OB_Get = 1224;
        PA_Variable prm_OB_Get[2];
        prm_OB_Get[0] = _4D;
        prm_OB_Get[1] = PA_CreateVariable(eVK_Unistring);
        C_TEXT pp;
        pp.setUTF8String((const uint8_t *)"Blob", 4);
        PA_Unistring BLOB = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());
        PA_SetStringVariable(&prm_OB_Get[1], &BLOB);//DO NOT call PA_DisposeUnistring
        PA_Variable _4D_Blob = PA_ExecuteCommandByID(cmd_OB_Get, prm_OB_Get, 2);
        PA_ClearVariable(&prm_OB_Get[1]);//BLOB belongs to variable. no need to dispose
        
        const int cmd_OB_Instance_of = 1731;
        PA_Variable prm_OB_Instance_of[2];
        prm_OB_Instance_of[0] = PA_CreateVariable(eVK_Object);
        prm_OB_Instance_of[1] = _4D_Blob;
        PA_SetObjectVariable(&prm_OB_Instance_of[0], f);
        PA_Variable status = PA_ExecuteCommandByID(cmd_OB_Instance_of, prm_OB_Instance_of, 2);
        bool isBlob = PA_GetBooleanVariable(status);
        if(isBlob) {

            pp.setUTF8String((const uint8_t *)"size", 4);
            PA_Unistring SIZE = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());//PA_DisposeUnistring
            PA_Variable _s = PA_GetObjectProperty(f, &SIZE);
            PA_long32 size = PA_GetRealVariable(_s);
            PA_DisposeUnistring(&SIZE);
            PA_ClearVariable(&_s);
            
            PA_Variable blob = PA_CreateVariable(eVK_Blob);
            
            const int cmd_COPY_BLOB = 558;
            PA_Variable prm_COPY_BLOB[5];
            prm_COPY_BLOB[0] = prm_OB_Instance_of[0];
            prm_COPY_BLOB[1] = blob;
            prm_COPY_BLOB[2] = PA_CreateVariable(eVK_Longint);
            prm_COPY_BLOB[3] = PA_CreateVariable(eVK_Longint);
            prm_COPY_BLOB[4] = PA_CreateVariable(eVK_Longint);
            
            PA_SetLongintVariable(&prm_COPY_BLOB[2], 0);
            PA_SetLongintVariable(&prm_COPY_BLOB[3], 0);
            PA_SetLongintVariable(&prm_COPY_BLOB[4], size);
            
            PA_ExecuteCommandByID(cmd_COPY_BLOB, prm_COPY_BLOB, 5);
            
            data.resize(size);
            PA_GetBlobVariable(blob, &data[0]);

            PA_ClearVariable(&prm_COPY_BLOB[1]);//blob
            PA_ClearVariable(&prm_COPY_BLOB[2]);
            PA_ClearVariable(&prm_COPY_BLOB[3]);
            PA_ClearVariable(&prm_COPY_BLOB[4]);
        }
        
        PA_ClearVariable(&prm_OB_Instance_of[0]);
        return isBlob;
    }
    
    return false;
}

static bool file_object_to_path(PA_ObjectRef f, std::string& path) {
    
    return _object_to_path(f, path, 1566 /*4D.File*/);
}

static bool folder_object_to_path(PA_ObjectRef f, std::string& path) {
    
    return _object_to_path(f, path, 1567 /*4D.Folder*/);
}

#pragma mark -

// Pick the smallest bucket that fits token_count, with a penalty
// that discourages crossing the performance cliff.
//
// Scoring: score = fill_ratio - cliff_penalty * (bucket > cliff ? 1 : 0)
// The bucket with the highest score that still fits is chosen.
//
// cliff_penalty=0.15 means a sub-cliff bucket must be at least 15% less
// efficient before the picker crosses the cliff.  At 0.0 it always picks
// the smallest fitting bucket regardless of cliff.

/*
static uint32_t pick_bucket(uint32_t token_count,
                             uint32_t cliff        = 1000,
                             float    cliff_penalty = 0.15f)
{
    static constexpr uint32_t kBuckets[] =
        { 256, 512, 768, 1024, 2048, 3072, 4096, 8192, 16384 };

    uint32_t best       = 0;
    float    best_score = -1.0f;

    for (uint32_t b : kBuckets) {
        if (b < token_count) continue;          // doesn't fit
        float fill       = static_cast<float>(token_count) / b;
        float over_cliff = (b > cliff) ? 1.0f : 0.0f;
        float score      = fill - cliff_penalty * over_cliff;
        if (score > best_score) { best_score = score; best = b; }
    }

    // token_count > 32768: caller must split first
    return best;
}
*/

static void ob_append_n(PA_CollectionRef c, double value) {
    
    PA_Variable v = PA_CreateVariable(eVK_Real);
    PA_SetRealVariable(&v, value);
    PA_SetCollectionElement(c, PA_GetCollectionLength(c), v);
    PA_ClearVariable(&v);
}

static void ob_append_c(PA_CollectionRef c, PA_CollectionRef value) {

    PA_Variable v = PA_CreateVariable(eVK_Collection);
    PA_SetCollectionVariable(&v, value);
    PA_SetCollectionElement(c, PA_GetCollectionLength(c), v);
    PA_ClearVariable(&v);
}

using TokenArray = std::vector<int>;
using TokenMatrix = std::vector<TokenArray>;

static void ob_append_s(PA_CollectionRef c, const std::string& value) {
    
    C_TEXT t;
    t.setUTF8String((const uint8_t *)value.c_str(), (uint32_t)value.length());
    PA_Variable v = PA_CreateVariable(eVK_Unistring);
    PA_Unistring u = PA_CreateUnistring((PA_Unichar *)t.getUTF16StringPtr());
    PA_SetStringVariable(&v, &u);
    PA_SetCollectionElement(c, PA_GetCollectionLength(c), v);
    PA_ClearVariable(&v);
}

// Internal representation before conversion to PA_Collection
struct Chunk {
    std::vector<int> tokens;   // always exactly `length` tokens (or shorter if !token_padding)
    std::string      text;     // only populated when retokenize == true
};

static std::vector<Chunk> build_chunks(
    const std::vector<int>& raw,
    const uint32_t          length,
    const float             overlap_pct,   // e.g. 0.09f
    const bool              token_padding,
    const bool              retokenize,
    const PoolingMode       pooling
) {
    if (raw.empty() || length == 0)
        return {};

    const int pad   = gpadtoken_id;
    const int n     = (int)raw.size();

    // overlap in tokens, stride = non-overlapping advance per chunk
    const int overlap = (int)std::round(length * overlap_pct);
    const int stride  = (int)length - overlap;   // must be > 0
    assert(stride > 0 && "overlap_pct must be < 1.0");

    std::vector<Chunk> result;

    for (int start = 0; start < n; start += stride) {
        const int end        = std::min(start + (int)length, n);
        const int real_count = end - start;
        const bool is_last   = (end >= n);
        const bool needs_pad = is_last && token_padding && (real_count < (int)length);

        Chunk chunk;

        if (!needs_pad) {
            // Full chunk, or last chunk without padding
            chunk.tokens.assign(raw.begin() + start, raw.begin() + end);

        } else if (pooling == PoolingMode::LastToken) {
            // Left-pad: pad tokens first, then real tokens
            // So the last real token lands at index (length - 1)
            chunk.tokens.resize(length, pad);
            int pad_count = (int)length - real_count;
            std::copy(raw.begin() + start,
                      raw.begin() + end,
                      chunk.tokens.begin() + pad_count);

        } else {
            // Right-pad: real tokens first, then pad tokens
            // Correct for CLS (position 0 is always real) and Mean (mask pads out)
            chunk.tokens.reserve(length);
            chunk.tokens.insert(chunk.tokens.end(),
                                raw.begin() + start,
                                raw.begin() + end);
            chunk.tokens.resize(length, pad);
        }

        if (retokenize) {
            chunk.text = gchunker->detokenize(chunk.tokens);
            chunk.tokens.clear();   // not needed when returning strings
        }

        result.push_back(std::move(chunk));

        // If the entire input fit in the first chunk we're done
        if (is_last) break;
    }

    return result;
}

static PA_CollectionRef chunks_to_collection(const std::vector<Chunk>& chunks,
                                              const bool retokenize)
{
    PA_CollectionRef result = PA_CreateCollection();
    for (PA_long32 i = 0; i < (PA_long32)chunks.size(); i++) {
        if (retokenize) {
            ob_append_s(result, chunks[i].text);
        } else {
            PA_CollectionRef inner = PA_CreateCollection();
            for (PA_long32 j = 0; j < (PA_long32)chunks[i].tokens.size(); j++)
                ob_append_n(inner, chunks[i].tokens[j]);
            ob_append_c(result, inner);
        }
    }
    return result;
}

static PA_CollectionRef tokenize(
    const std::string& text,
    const uint32_t     length,
    const bool         token_padding,
    const bool         retokenize,
    const float        overlap_pct,
    const PoolingMode  pooling
) {
    auto make_empty = [&]() {
        PA_CollectionRef r = PA_CreateCollection();
        if (retokenize) ob_append_s(r, "");
        else {
            PA_CollectionRef inner = PA_CreateCollection();
            for (uint32_t i = 0; i < length; i++) ob_append_n(inner, gpadtoken_id);
            ob_append_c(r, inner);
        }
        return r;
    };

    if (!gchunker || text.empty())
        return make_empty();

    // Tokenize to raw int vector
    std::vector<int> raw;
    try {
        auto tokens = gchunker->tokenize(text);
        raw.reserve(tokens.size());
        for (auto t : tokens) raw.push_back((int)t);
    } catch (const std::exception& e) {
        std::fprintf(stderr, "ERROR tokenize failed: %s\n", e.what());
        return make_empty();
    }

    if (raw.empty())
        return make_empty();

    auto chunks = build_chunks(raw, length, overlap_pct, token_padding, retokenize, pooling);
    return chunks_to_collection(chunks, retokenize);
}

PA_CollectionRef process_paragraph(
    const std::string& paragraph,
    const uint32_t     length,
    const bool         token_padding,
    const bool         retokenize,
    const float        overlap_pct,
    const int  pooling
) {
    return tokenize(paragraph, length, token_padding, retokenize, overlap_pct, (PoolingMode)pooling);
}

PA_CollectionRef process_paragraphs(
    const std::vector<std::string>& paragraphs,
    const uint32_t                  length,
    const bool                      token_padding,
    const bool                      retokenize,
    const float                     overlap_pct,
    const int               pooling
) {
    PA_CollectionRef result = PA_CreateCollection();
    for (const auto& paragraph : paragraphs) {
        auto chunks = [&]() -> std::vector<Chunk> {
            // re-use build_chunks directly to avoid double PA_Collection conversion
            if (!gchunker || paragraph.empty()) return {};
            std::vector<int> raw;
            try {
                auto tokens = gchunker->tokenize(paragraph);
                for (auto t : tokens) raw.push_back((int)t);
            } catch (...) { return {}; }
            if (raw.empty()) return {};
            return build_chunks(raw, length, overlap_pct, token_padding, retokenize, (PoolingMode)pooling);
        }();

        for (PA_long32 i = 0; i < (PA_long32)chunks.size(); i++) {
            if (retokenize) {
                ob_append_s(result, chunks[i].text);
            } else {
                PA_CollectionRef inner = PA_CreateCollection();
                for (auto tok : chunks[i].tokens) ob_append_n(inner, tok);
                ob_append_c(result, inner);
            }
        }
    }
    return result;
}

void Extract_SET_OPTION(PA_PluginParameters params) {
    
    option_type  ot = (option_type) PA_GetLongParameter(params, 1);
    PA_ObjectRef model = PA_GetObjectParameter(params, 2);
    switch (ot) {
        case option_type_tokenizer_file:
            {
                if (model) {
                    std::string path;
                    if (file_object_to_path(model, path)) {

                        std::ifstream f(path, std::ios::binary);
                        if (f) {
                            std::ostringstream ss;
                            ss << f.rdbuf();
                            std::string etd = ss.str();
                        
                            chunker::ModelConfig model_cfg;
                            model_cfg.model_path = path;
                            model_cfg.verbosity  = 1;

                            try {
                                gchunker = chunker::make_chunker(model_cfg);
                                gpadtoken_id = gchunker->pad_token_id_internal();
                            } catch (const std::exception& e) {
                                std::fprintf(stderr, "ERROR initialising chunker: %s\n", e.what());
                            }

                        }
                    }
                }
            }
            break;
            
        default:
            break;
    }
    
}

void Extract(PA_PluginParameters params) {

    PA_ObjectRef returnValue = PA_CreateObject();
    ob_set_b(returnValue, L"success", false);
    
    input_type  it = (input_type) PA_GetLongParameter(params, 1);
    output_type ot = (output_type)PA_GetLongParameter(params, 2);
    
    PA_ObjectRef document = PA_GetObjectParameter(params, 3);
    if (document) {
                
        std::vector<uint8_t>data;
        CUTF8String _password;
        std::string password;
        if(ob_get_s(document, L"password", &_password))
           password = (const char *)_password.c_str();
        
        CUTF8String _charset;
        std::string charset = "iso-8859-1";
        if(ob_get_s(document, L"charset", &_charset))
            charset = (const char *)_charset.c_str();
        
        int max_paragraph_length = -1;
        if(ob_is_defined(document, L"max_paragraph_length")) {
            int intValue = (int)ob_get_n(document, L"max_paragraph_length");
            if(intValue > 0) {
                max_paragraph_length = intValue;
            }
        }
        
        bool unique_values_only = false;
        if(ob_is_defined(document, L"unique_values_only")) {
            unique_values_only = ob_get_b(document, L"unique_values_only");
        }
        
        bool text_as_tokens = false;
        if(ob_is_defined(document, L"text_as_tokens")) {
            text_as_tokens = ob_get_b(document, L"text_as_tokens");
        }
        int tokens_length = 1024;
        if(ob_is_defined(document, L"tokens_length")) {
            int intValue = (int)ob_get_n(document, L"tokens_length");
            if(intValue > 0) {
                tokens_length = intValue;
            }
        }
        bool token_padding = false;
        if(ob_is_defined(document, L"token_padding")) {
            token_padding = ob_get_b(document, L"token_padding");
        }
        PoolingMode pooling_mode = PoolingMode::Mean;
        if(ob_is_defined(document, L"pooling_mode")) {
            int intValue = (int)ob_get_n(document, L"pooling_mode");
            if(intValue > 0) {
                pooling_mode = (PoolingMode)intValue;
            }
        }
        float overlap_ratio = 0.09;
        if(ob_is_defined(document, L"overlap_ratio")) {
            float floatValue = (float)ob_get_n(document, L"overlap_ratio");
            if ((floatValue > 0) && (floatValue < 1)) {
                overlap_ratio = floatValue;
            }
        }
        
        PA_ObjectRef file = ob_get_o(document, L"file");
        std::string path;
        if (file) {
            if (file_object_to_path(file, path)) {
#if VERSIONWIN
                C_TEXT t;
                t.setUTF8String((const uint8_t *)path.c_str(), path.length());
                FILE* f = _fopen((const wchar_t *)t.getUTF16StringPtr(), _rb);
#else
                FILE* f = _fopen(path.c_str(), _rb);
#endif
                if(f) {
                    _fseek(f, 0, SEEK_END);
                    size_t len = (size_t)_ftell(f);
                    _fseek(f, 0, SEEK_SET);
                    data.resize(len);
                    fread(data.data(), 1, data.size(), f);
                    fclose(f);
                }
            }
            if(data.size()) {
                switch (it) {
                    case input_type_xlsx:
                    case input_type_docx:
                    case input_type_pptx:
                        opc_parse_data(data,
                                       returnValue,
                                       ot,
                                       max_paragraph_length,
                                       unique_values_only,
                                       text_as_tokens,
                                       tokens_length,
                                       token_padding,
                                       (int)pooling_mode,
                                       overlap_ratio,
                                       password);
                        break;
                    case input_type_pdf:
                        pdfium_parse_data(data,
                                          returnValue,
                                          ot,
                                          max_paragraph_length,
                                          unique_values_only,
                                          text_as_tokens,
                                          tokens_length,
                                          token_padding,
                                          (int)pooling_mode,
                                          overlap_ratio,
                                          password);
                        break;
                    case input_type_xls:
                        xls_parse_data(data,
                                       returnValue,
                                       ot,
                                       max_paragraph_length,
                                       unique_values_only,
                                       text_as_tokens,
                                       tokens_length,
                                       token_padding,
                                       (int)pooling_mode,
                                       overlap_ratio,
                                       charset);
                        break;
                    case input_type_txt:
                        txt_parse_data(data,
                                       returnValue,
                                       ot,
                                       max_paragraph_length,
                                       unique_values_only,
                                       text_as_tokens,
                                       tokens_length,
                                       token_padding,
                                       (int)pooling_mode,
                                       overlap_ratio);
                        break;
                    default:
                        break;
                }
            }
        }
    }
    PA_ReturnObject(params, returnValue);
}

static void OnExit() {

    if (gchunker) {
        gchunker.reset();
    }
    
    FPDF_DestroyLibrary();
}
