/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Universal-Document-Parser.h
 #	source generated by 4D Plugin Wizard
 #	Project : Universal Document Parser
 #	author : miyako
 #	2026/03/30
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_UNIVERSAL_DOCUMENT_PARSER_H
#define PLUGIN_UNIVERSAL_DOCUMENT_PARSER_H

#include "4DPluginAPI.h"

#include <string>
#include <chrono>
#include <cstdio>
#include <ctime>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <numeric>
#include <random>
#include <functional>
#include <filesystem>
#include <vector>
#include <exception>
#include <sstream>
#include <iostream>
#include <fstream>
#include <thread>
#include <algorithm>
#include <cassert>
#include <stdexcept>
#include <functional>

#include <stdio.h>
#include <stdlib.h>

#include "pdfium-parser.h"
#include "opc-parser.h"
#include "xls-parser.h"
#include "txt-parser.h"
#include "tidy-parser.h"
#include "olecf-parser.h"
#include "md-parser.h"
#include "chunker.h"

typedef enum {
    input_type_xlsx = 0,
    input_type_docx,
    input_type_pptx,
    input_type_xls,
    input_type_doc,
    input_type_ppt,
    input_type_pdf,
    input_type_msg,
    input_type_eml,
    input_type_rtf,
    input_type_html,
    input_type_txt,
    input_type_md
}input_type;

typedef enum {
    option_type_tokenizer_file = 0
}option_type;

#pragma mark -

void Extract(PA_PluginParameters params);
void Extract_SET_OPTION(PA_PluginParameters params);

#ifdef _WIN32
    extern HMODULE ghmodule;
#endif

enum class PoolingMode {
    Mean,       // encoder-only, mean pool  – no padding needed
    CLS,        // encoder-only, CLS        – right-pad (real tokens first)
    LastToken   // decoder-only             – left-pad  (real tokens last)
};

PA_CollectionRef process_paragraph(
                                   const std::string& paragraph,
                                   const uint32_t     length,
                                   const bool         token_padding,
                                   const bool         retokenize,
                                   const float        overlap_pct = 0.09f,
                                   const int  pooling     = (int)PoolingMode::LastToken
                                   );

PA_CollectionRef process_paragraphs(
                                    const std::vector<std::string>& paragraphs,
                                    const uint32_t                  length,
                                    const bool                      token_padding,
                                    const bool                      retokenize,
                                    const float                     overlap_pct = 0.09f,
                                    const int               pooling     = (int)PoolingMode::LastToken
                                    );

static void OnStartup();
static void OnExit();

void ob_append_s(PA_CollectionRef c, const std::string& value);
void ob_append_o(PA_CollectionRef c, PA_ObjectRef value);
void ob_append_c(PA_CollectionRef c, PA_CollectionRef value);
void ob_append_n(PA_CollectionRef c, double value);

#endif /* PLUGIN_UNIVERSAL_DOCUMENT_PARSER_H */
